### ISSUE TITLE
factom-cli can go into an infinite loop printing entry data

### ISSUE THREAD

**Issue by tom-seddon** [FactomProject/factom-cli#2]
See https://github.com/FactomProject/factom-cli/blob/master/get.go#L176 - I think that line should be this:

```
p = p[16:]
```

(sorry, I've no idea how to make a pull request for stuff retrieved by `go get` yet!)

Thanks,

--Tom

**Comment by michaelbeam** [comment]
Thanks Tom. I have removed that whole formatting section (it was trying to do something clever that it shouldn't have) and replaced it with a simpler printing line.

For our project because we have so many git repos that we work on, we have a dedicated git repo for our issue tracking. In the future please put any issue items into github.com/FactomProject/WorkItems
